name: SweetChat
version: '${version}'
main: top.mrxiaom.sweet.chat.SweetChat
api-version: 1.13
depend: []
softdepend:
  - PlaceholderAPI
  - LangUtils
  - packetevents
  - TAB
authors: [ MrXiaoM ]
folia-supported: true
libraries:
  - "org.jetbrains:annotations:24.0.0"
commands:
  sweetchat:
    description: 'The main command of SweetChat'
    aliases: [ schat, sc, chat ]
